# Generated by Django 4.0.4 on 2022-06-08 08:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profile_api', '0003_profilefeeditem'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountToFeedBookmark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_feed_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='profile_api.profilefeeditem')),
            ],
            options={
                'db_table': 'account_to_feed_bookmark',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='userprofile',
            name='bookmarked_feed',
            field=models.ManyToManyField(blank=True, through='profile_api.AccountToFeedBookmark', to='profile_api.profilefeeditem'),
        ),
        migrations.AddField(
            model_name='accounttofeedbookmark',
            name='user_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='accounttofeedbookmark',
            constraint=models.UniqueConstraint(fields=('user_profile_id', 'profile_feed_item_id'), name='profile_feed_profile_feed_unique'),
        ),
    ]
